course_name = "机器视觉"
repo_type = "normal"
course_code = "AUTO3006"
description = "机器视觉课程资料。"

[[lecturers]]
name = "吴晓军"

[[lecturers.reviews]]
content = """
授课风格：读ppt
是否需要认真听讲做笔记：不需要
听课建议：部分思路对于未来想要研究图形学、计算机图形学、计算机视觉、机器视觉领域的同学有所启发，不忙的时候可以听，模板匹配NCC部分讲的比较精彩
"""

[[lecturers]]
name = "胡靓"

[[lecturers.reviews]]
content = """
授课风格：读ppt，偶尔会拓展一些该领域的课外知识
是否需要认真听讲做笔记：前半段课程不需要，后半段（算法部分）建议认真听，无需笔记
听课建议：机器视觉的内容和大部分视觉课程类似，对于自动化专业，未来不可避免接触工业界（机器人、无人驾驶等），视觉技术非常重要，这门课的内容属于基础知识，建议掌握
"""

[[lecturers]]
name = "龚有敏"

[[lecturers.reviews]]
content = "授课风格：年轻，读ppt，无聊，解释清晰，答疑认真。"


[[sections]]
title = "关于考试"

[[sections.items]]
content = """
考试难度：中等

如果有视觉相关知识基础，这门课的内容将会非常简单，但实验涉及复杂的环境配置，需要仔细阅读《实验指导书》。
"""
author = { name = "Tanglongbin", link = "https://github.com/tanglongbin", date = "" }

[[sections.items]]
content = "性价比高，必选。"
author = { name = "Tanglongbin", link = "https://github.com/tanglongbin", date = "" }

[[sections.items]]
content = "2024更新：21级学生给分普遍较低，且出现挂科现象。有出国意向同学慎选。"
author = { name = "Oliver Wu", link = "https://github.com/OliverWu515", date = "2024-01" }


[[sections]]
title = "关于实验"

[[sections.items]]
content = "实验课老师很好说话，实验也相对其他科目有趣，总体不错。"
author = { name = "Tanglongbin", link = "https://github.com/tanglongbin", date = "" }


[[sections]]
title = "关于代码"

[[sections.items]]
content = "这门课的成绩构成很大部分直接和代码挂钩，包括作业和课设。为杜绝抄袭现象，经作者 黄继凡 和 Sieroy 的同意，源代码已删除，仅保留解题思路和输出结果。"
